### ISSUE TITLE
Fix 'prevent-fetch', 'prevent-xhr' — error on blocked request

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#334] opened 2023-06-28 10:38 UTC
The main problem - now this scriplet does not help if a request/domain is blocked by DNS filtering.
Affected more than 300 rules.

### Steps to reproduce

1. Disable Tracking Protection filter and add `yext-pixel.com` to user rules.
2. Open `https://clinics.vippetcare.com/al/birmingham/1928-montgomery-hwy./db089214-36a7-45a8-8f4e-6a14d7c5f17c`
3. Click `View Pricing` button
=> It does not work, because `yext-pixel.com` is blocked (in my case - by DNS).
4. Add `vippetcare.com#%#//scriptlet('prevent-fetch', 'www.yext-pixel.com')`

### Actual behavior

Scripltetdoes not intercept `fetch` request, and the button does not work.

### Expected behavior

The rule must work like in 4.1.55, where no request when added that rule, and the button is not broken because of blocking request.

**Comment by Alex-302** [comment] 2023-06-28 10:38
Not sure if `prevent-xhr` has the same problem.

**Comment by AdamWr** [comment] 2023-06-28 11:20
If I'm not wrong the problem is in this line:
https://github.com/AdguardTeam/Scriptlets/blob/e7295bd67b876787ffbc48b69482aac406569565/src/scriptlets/prevent-fetch.js#L148
It tries to fetch a content, but request is blocked.

Simple test case:
1. Add these rules:
```adblock
||example.org^$xmlhttprequest
example.org#%#//scriptlet('prevent-fetch', '/')
```
2. Go to - `https://example.org/`
3. Run this script in console:
<details><summary>Code:</summary>

```js
new Promise((resolve, reject) => {
  return fetch('/').then(response => {
    if (response.ok) {
        console.log('OK test');
      resolve(response)
    } else {
      reject(new Error('error'))
    }
  }, error => {
    reject(new Error(error.message))
  })
})
```

</details>

There should message in the console `OK test`, but with latest version of scriptlet it's blocked and there is an error.

**Comment by Alex-302** [comment] 2023-07-20 12:13
Another problem:
when all filters are turned off, and added `technofino.in#%#//scriptlet('prevent-fetch', 'pagead2.googlesyndication.com')`, the site detects ad blocker
https://www.technofino.in/community/threads/how-to-apply-for-hsbc-credit-card-for-non-serviceable-address-pincode.1991/

**Comment by AdamWr** [comment] 2023-07-20 13:17
According to my tests, it should be fixed with latest changes.

**Closed** 2023-07-24 09:16 UTC
Labels: bug, Resolution: Fixed, Status: Resolved, Version: Scriptlets v1.9, Priority: P2, Release: v1.9.57

**Comment by Alex-302** [comment] 2023-07-24 11:18
Yes, works fine with dev build.
