### ISSUE TITLE
prevent-bab traps DDoS protection and causes the page stuck

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#84] opened 2020-05-14 10:17 UTC
### URL(s) where the issue occurs

`http://reevown.com/`

### Describe the issue

Cloudflare's DDoS protection never stops its job if prevent-bab is applied to the page.

### Steps to reproduce

1. Enable AdGuard Base.
2. Visit the URL

### Screenshot(s)

![prevent-bab](https://user-images.githubusercontent.com/58900598/81922588-4ee0f000-9617-11ea-903c-20d7676069da.png)

### Versions

- Browser/version: Firefox 76.0.1
- AdGuard version: 3.4.19

### Settings

- AdGuard Base only, Stealth Mode disabled

### Notes

uBO issue: https://github.com/uBlockOrigin/uAssets/issues/7403

**Comment by AdamWr** [comment] 2020-05-14 10:21
It seems that it's a duplicate of https://github.com/AdguardTeam/Scriptlets/issues/21

**Comment by slavaleleka** [comment] 2020-05-14 10:25
yes, that's well known issue which [can not be fixed](https://github.com/AdguardTeam/Scriptlets/issues/21#issuecomment-619018431)

@Yuki2718 prevent-bab works exactly like it should in order to circumvent blockAdBlock script and DDoS protection by Cloudflare is broken by that

**Closed by slavaleleka** 2020-05-14 10:25 UTC

**Comment by Yuki2718** [comment] 2020-05-14 10:29
Sorry, I should have searched for the known issue first.
